--- #YAML:1.0
name:               Text-Names
version:            0.08
abstract:           Perl extension for name parsing and normalization
author:
    - David Bourget
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:           0.96
    Text::Capitalize:     1.1
    Text::LevenshteinXS:  0.03
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
